services:
  proxy:
    build:
      target: proxy
    container_name: workshop-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      registry:
        condition: service_healthy
      fileserver:
        condition: service_healthy
      ui:
        condition: service_healthy
    networks:
      - internal
  registry:
    build:
      target: registry
    container_name: workshop-registry
    restart: always
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - internal
  fileserver:
    build:
      target: fileserver
    container_name: workshop-fileserver
    restart: always
    networks:
      - internal
  ui:
    build:
      target: ui
    container_name: workshop-ui
    environment:
      - REGISTRY_URL=https://registry.labs.dae.mn
    networks:
      - internal
networks:
  internal:
    driver: bridge
volumes:
  registry-data: null
